name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Build binaries
      run: |
        go build -o gitd_linux_amd64 
        GOOS=windows GOARCH=amd64 go build -o gitd_windows_amd64.exe

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          gitd_linux_amd64
          gitd_windows_amd64.exe
